// <auto-generated>
//     This stub mirrors the Visual Studio ResX code-gen output. Each property reads the
//     matching key out of the Strings.resx resource family at call time, so callers that
//     wire {x:Static loc:Strings.Foo} pick up the canonical English source. Live runtime
//     culture switching uses LocalizationService.Default (an INotifyPropertyChanged
//     ILocalizationService) instead of touching the Strings cache here.
//
//     If the resx ever sprouts a real Designer.cs file from VS, delete this stub - the
//     visual-studio-generated file supersedes it. Keys are produced one-to-one.
// </auto-generated>
#nullable enable

using System.Globalization;
using System.Resources;

namespace TechTeaStudio.HyperionMinecraftLauncher.App.Localization;

/// <summary>
/// Strongly-typed accessor for every UI string in <c>Strings.resx</c>. AXAML files reference
/// these as <c>{x:Static loc:Strings.SomeKey}</c>; at runtime the value comes back from the
/// underlying <see cref="ResourceManager"/> with the current UI culture (or the canonical
/// English fallback when a translation is missing).
/// </summary>
public static class Strings
{
    private static readonly ResourceManager _rm = new(
        "TechTeaStudio.HyperionMinecraftLauncher.App.Localization.Strings",
        typeof(Strings).Assembly);

    /// <summary>
    /// The shared <see cref="ResourceManager"/> over the launcher's <c>Strings.resx</c>
    /// resource family. <see cref="App.LocalizationService"/> uses this to build the
    /// runtime <c>ILocalizationService</c>.
    /// </summary>
    public static ResourceManager ResourceManager => _rm;

    private static string L(string key) =>
        _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    // ============================== MainWindow ==============================
    public static string MainWindow_Title => L("MainWindow.Title");
    public static string MainWindow_HeaderTitle => L("MainWindow.HeaderTitle");

    public static string Header_SignInWithMicrosoft => L("Header.SignInWithMicrosoft");
    public static string Header_AccountsLabel => L("Header.AccountsLabel");
    public static string Header_AddAccount => L("Header.AddAccount");
    public static string Header_RemoveThisAccount => L("Header.RemoveThisAccount");

    public static string WindowChrome_Minimize => L("WindowChrome.Minimize");
    public static string WindowChrome_MaximizeRestore => L("WindowChrome.MaximizeRestore");
    public static string WindowChrome_Close => L("WindowChrome.Close");
    public static string WindowChrome_Dismiss => L("WindowChrome.Dismiss");

    // Sidebar
    public static string Sidebar_CollapseExpand => L("Sidebar.CollapseExpand");
    public static string Sidebar_Home => L("Sidebar.Home");
    public static string Sidebar_Installations => L("Sidebar.Installations");
    public static string Sidebar_Skins => L("Sidebar.Skins");
    public static string Sidebar_Servers => L("Sidebar.Servers");
    public static string Sidebar_Headless => L("Sidebar.Headless");
    public static string Sidebar_HeadlessTooltip => L("Sidebar.HeadlessTooltip");
    public static string Sidebar_Mods => L("Sidebar.Mods");
    public static string Sidebar_News => L("Sidebar.News");
    public static string Sidebar_Settings => L("Sidebar.Settings");
    public static string Sidebar_Logs => L("Sidebar.Logs");
    public static string Sidebar_ParityBuildLabel => L("Sidebar.ParityBuildLabel");

    // Home
    public static string Home_Title => L("Home.Title");
    public static string Home_Subtitle => L("Home.Subtitle");
    public static string Home_YourInstancesLabel => L("Home.YourInstancesLabel");
    public static string Home_YourInstancesPlaceholder => L("Home.YourInstancesPlaceholder");
    public static string Home_RescanButton => L("Home.RescanButton");
    public static string Home_OrInstallAnother => L("Home.OrInstallAnother");
    public static string Home_SearchVersionWatermark => L("Home.SearchVersionWatermark");
    public static string Home_ChipRelease => L("Home.ChipRelease");
    public static string Home_ChipSnapshot => L("Home.ChipSnapshot");
    public static string Home_ChipOldBeta => L("Home.ChipOldBeta");
    public static string Home_ChipOldAlpha => L("Home.ChipOldAlpha");
    public static string Home_ManifestPlaceholder => L("Home.ManifestPlaceholder");
    public static string Home_RefreshManifestButton => L("Home.RefreshManifestButton");
    public static string Home_OfflineUsernameLabel => L("Home.OfflineUsernameLabel");
    public static string Home_OfflineUsernameWatermark => L("Home.OfflineUsernameWatermark");
    public static string Home_ResumeWorldButton => L("Home.ResumeWorldButton");
    public static string Home_ResumeWorldTooltip => L("Home.ResumeWorldTooltip");
    public static string Home_LaunchButton => L("Home.LaunchButton");

    // Installations
    public static string Installations_Title => L("Installations.Title");
    public static string Installations_Subtitle => L("Installations.Subtitle");
    public static string Installations_NewInstance => L("Installations.NewInstance");
    public static string Installations_ImportFromZip => L("Installations.ImportFromZip");
    public static string Installations_ImportFromZipTooltip => L("Installations.ImportFromZipTooltip");
    public static string Installations_ImportModpack => L("Installations.ImportModpack");
    public static string Installations_Refresh => L("Installations.Refresh");
    public static string Installations_DeleteSelected => L("Installations.DeleteSelected");
    public static string Installations_AutoBadge => L("Installations.AutoBadge");
    public static string Installations_MoreTooltip => L("Installations.MoreTooltip");
    public static string Installations_MenuEditInstance => L("Installations.MenuEditInstance");
    public static string Installations_MenuChangeIcon => L("Installations.MenuChangeIcon");
    public static string Installations_MenuExportToZip => L("Installations.MenuExportToZip");
    public static string Installations_MenuOpenFolder => L("Installations.MenuOpenFolder");
    public static string Installations_MenuDelete => L("Installations.MenuDelete");

    // Instance detail tabs
    public static string InstanceTabs_Screenshots => L("InstanceTabs.Screenshots");
    public static string InstanceTabs_Worlds => L("InstanceTabs.Worlds");
    public static string InstanceTabs_Servers => L("InstanceTabs.Servers");
    public static string InstanceTabs_Crashes => L("InstanceTabs.Crashes");
    public static string InstanceTabs_RefreshButton => L("InstanceTabs.RefreshButton");
    public static string InstanceTabs_OpenFolderButton => L("InstanceTabs.OpenFolderButton");
    public static string InstanceTabs_NoCrashReports => L("InstanceTabs.NoCrashReports");
    public static string InstanceTabs_SearchModrinth => L("InstanceTabs.SearchModrinth");
    public static string InstanceTabs_SearchCurseForge => L("InstanceTabs.SearchCurseForge");
    public static string InstanceTabs_WorldMenuBackupNow => L("InstanceTabs.WorldMenuBackupNow");
    public static string InstanceTabs_WorldMenuRestoreLatest => L("InstanceTabs.WorldMenuRestoreLatest");
    public static string InstanceTabs_WorldMenuOpenFolder => L("InstanceTabs.WorldMenuOpenFolder");
    public static string InstanceTabs_CrashSeparatorDash => L("InstanceTabs.CrashSeparatorDash");
    public static string InstanceTabs_ResourcePacks => L("InstanceTabs.ResourcePacks");
    public static string InstanceTabs_ShaderPacks => L("InstanceTabs.ShaderPacks");
    public static string InstanceTabs_DataPacks => L("InstanceTabs.DataPacks");
    public static string InstanceTabs_PackEnableTooltip => L("InstanceTabs.PackEnableTooltip");
    public static string InstanceTabs_PackRemoveButton => L("InstanceTabs.PackRemoveButton");
    public static string InstanceTabs_PackEmptyResource => L("InstanceTabs.PackEmptyResource");
    public static string InstanceTabs_PackEmptyShader => L("InstanceTabs.PackEmptyShader");
    public static string InstanceTabs_PackEmptyData => L("InstanceTabs.PackEmptyData");

    // Skins
    public static string Skins_Title => L("Skins.Title");
    public static string Skins_Subtitle => L("Skins.Subtitle");
    public static string Skins_UploadButton => L("Skins.UploadButton");
    public static string Skins_CapeLabel => L("Skins.CapeLabel");
    public static string Skins_CapeNonePlaceholder => L("Skins.CapeNonePlaceholder");
    public static string Skins_ClearCape => L("Skins.ClearCape");
    public static string Skins_RecentSkins => L("Skins.RecentSkins");
    public static string Skins_RecentReapplyTooltip => L("Skins.RecentReapplyTooltip");
    public static string Skins_DragHint => L("Skins.DragHint");

    // NameMC skin browser (T-namemc, v0.32.1).
    public static string SkinsBrowser_SectionTitle => L("SkinsBrowser.SectionTitle");
    public static string SkinsBrowser_SearchWatermark => L("SkinsBrowser.SearchWatermark");
    public static string SkinsBrowser_ShowTrending => L("SkinsBrowser.ShowTrending");
    public static string SkinsBrowser_ApplyButton => L("SkinsBrowser.ApplyButton");
    public static string SkinsBrowser_PoweredBy => L("SkinsBrowser.PoweredBy");
    public static string SkinsBrowser_FetchFailed => L("SkinsBrowser.FetchFailed");
    public static string SkinsBrowser_DownloadFailed => L("SkinsBrowser.DownloadFailed");
    public static string SkinsBrowser_Applying => L("SkinsBrowser.Applying");
    public static string SkinsBrowser_Loading => L("SkinsBrowser.Loading");
    public static string SkinsBrowser_NoResults => L("SkinsBrowser.NoResults");

    // Servers
    public static string Servers_Title => L("Servers.Title");
    public static string Servers_Subtitle => L("Servers.Subtitle");
    public static string Servers_RefreshServers => L("Servers.RefreshServers");
    public static string Servers_RefreshPings => L("Servers.RefreshPings");
    public static string Servers_JoinButton => L("Servers.JoinButton");
    public static string Servers_JoinTooltip => L("Servers.JoinTooltip");

    // Headless
    public static string HeadlessServers_Title => L("HeadlessServers.Title");
    public static string HeadlessServers_Subtitle => L("HeadlessServers.Subtitle");
    public static string HeadlessServers_NewServer => L("HeadlessServers.NewServer");
    public static string HeadlessServers_Refresh => L("HeadlessServers.Refresh");
    public static string HeadlessServers_Start => L("HeadlessServers.Start");
    public static string HeadlessServers_Stop => L("HeadlessServers.Stop");
    public static string HeadlessServers_Delete => L("HeadlessServers.Delete");
    public static string HeadlessServers_PlaceholderTooltip => L("HeadlessServers.PlaceholderTooltip");
    public static string HeadlessServers_FootnotePath => L("HeadlessServers.FootnotePath");
    public static string HeadlessServers_DashSeparator => L("HeadlessServers.DashSeparator");
    public static string HeadlessServers_MibAndPort => L("HeadlessServers.MibAndPort");

    // Mods
    public static string Mods_Title => L("Mods.Title");
    public static string Mods_Subtitle => L("Mods.Subtitle");
    public static string Mods_SourceModrinth => L("Mods.SourceModrinth");
    public static string Mods_SourceCurseForge => L("Mods.SourceCurseForge");
    public static string Mods_SearchLabel => L("Mods.SearchLabel");
    public static string Mods_SearchWatermark => L("Mods.SearchWatermark");
    public static string Mods_SearchButton => L("Mods.SearchButton");
    public static string Mods_SearchResults => L("Mods.SearchResults");
    public static string Mods_InstallButton => L("Mods.InstallButton");
    public static string Mods_InstalledInSelectedInstance => L("Mods.InstalledInSelectedInstance");
    public static string Mods_RefreshButton => L("Mods.RefreshButton");
    public static string Mods_PickAnInstanceFirst => L("Mods.PickAnInstanceFirst");
    public static string Mods_RightPaneHint => L("Mods.RightPaneHint");
    public static string Mods_RemoveButton => L("Mods.RemoveButton");
    public static string Mods_DownloadsCountFormat => L("Mods.DownloadsCountFormat");
    public static string Mods_FileSizeBytesFormat => L("Mods.FileSizeBytesFormat");

    // News
    public static string News_Title => L("News.Title");
    public static string News_Subtitle => L("News.Subtitle");
    public static string News_RefreshButton => L("News.RefreshButton");
    public static string News_ReadMore => L("News.ReadMore");

    // Settings
    public static string Settings_Title => L("Settings.Title");
    public static string Settings_Subtitle => L("Settings.Subtitle");
    public static string Settings_MemoryHeader => L("Settings.MemoryHeader");
    public static string Settings_MinimumXmsLabel => L("Settings.MinimumXmsLabel");
    public static string Settings_MaximumXmxLabel => L("Settings.MaximumXmxLabel");
    public static string Settings_MbUnit => L("Settings.MbUnit");
    public static string Settings_CeilingPrefix => L("Settings.CeilingPrefix");
    public static string Settings_CeilingSuffix => L("Settings.CeilingSuffix");
    public static string Settings_JvmArgsHeader => L("Settings.JvmArgsHeader");
    public static string Settings_JvmArgsWatermark => L("Settings.JvmArgsWatermark");
    public static string Settings_JvmArgsHint => L("Settings.JvmArgsHint");
    public static string Settings_GameDirHeader => L("Settings.GameDirHeader");
    public static string Settings_GameDirWatermark => L("Settings.GameDirWatermark");
    public static string Settings_BrowseButton => L("Settings.BrowseButton");
    public static string Settings_JavaExeHeader => L("Settings.JavaExeHeader");
    public static string Settings_JavaExeWatermark => L("Settings.JavaExeWatermark");
    public static string Settings_LauncherPrefsHeader => L("Settings.LauncherPrefsHeader");
    public static string Settings_KeepLauncherOpen => L("Settings.KeepLauncherOpen");
    public static string Settings_ShowGameLog => L("Settings.ShowGameLog");
    public static string Settings_BackupsHeader => L("Settings.BackupsHeader");
    public static string Settings_AutoBackupCheckbox => L("Settings.AutoBackupCheckbox");
    public static string Settings_KeepLatestNLabel => L("Settings.KeepLatestNLabel");
    public static string Settings_BackupHint => L("Settings.BackupHint");
    public static string Settings_LanguageHeader => L("Settings.LanguageHeader");
    public static string Settings_LanguageLabel => L("Settings.LanguageLabel");
    public static string Settings_LanguageUseSystemDefault => L("Settings.LanguageUseSystemDefault");
    public static string Settings_LanguageHint => L("Settings.LanguageHint");
    public static string Settings_SaveButton => L("Settings.SaveButton");

    // Logs
    public static string Logs_Title => L("Logs.Title");
    public static string Logs_Subtitle => L("Logs.Subtitle");
    public static string Logs_FilterWatermark => L("Logs.FilterWatermark");
    public static string Logs_RefreshButton => L("Logs.RefreshButton");
    public static string Logs_OpenLogsFolderButton => L("Logs.OpenLogsFolderButton");
    public static string Logs_CopyAllButton => L("Logs.CopyAllButton");

    // NewInstanceDialog
    public static string NewInstanceDialog_Title => L("NewInstanceDialog.Title");
    public static string NewInstanceDialog_HeaderTitle => L("NewInstanceDialog.HeaderTitle");
    public static string NewInstanceDialog_InstanceNameLabel => L("NewInstanceDialog.InstanceNameLabel");
    public static string NewInstanceDialog_DefaultInstanceName => L("NewInstanceDialog.DefaultInstanceName");
    public static string NewInstanceDialog_MinecraftVersionLabel => L("NewInstanceDialog.MinecraftVersionLabel");
    public static string NewInstanceDialog_SearchVersionWatermark => L("NewInstanceDialog.SearchVersionWatermark");
    public static string NewInstanceDialog_LoadingManifest => L("NewInstanceDialog.LoadingManifest");
    public static string NewInstanceDialog_FiltersSharedHint => L("NewInstanceDialog.FiltersSharedHint");
    public static string NewInstanceDialog_ModLoaderLabel => L("NewInstanceDialog.ModLoaderLabel");
    public static string NewInstanceDialog_LoaderVersionLabel => L("NewInstanceDialog.LoaderVersionLabel");
    public static string NewInstanceDialog_LoaderVersionPlaceholder => L("NewInstanceDialog.LoaderVersionPlaceholder");
    public static string NewInstanceDialog_LoaderHint => L("NewInstanceDialog.LoaderHint");
    public static string NewInstanceDialog_LoaderVanilla => L("NewInstanceDialog.LoaderVanilla");
    public static string NewInstanceDialog_LoaderFabric => L("NewInstanceDialog.LoaderFabric");
    public static string NewInstanceDialog_LoaderForge => L("NewInstanceDialog.LoaderForge");
    public static string NewInstanceDialog_LoaderNeoForge => L("NewInstanceDialog.LoaderNeoForge");
    public static string NewInstanceDialog_LoaderQuilt => L("NewInstanceDialog.LoaderQuilt");
    public static string NewInstanceDialog_IconLabel => L("NewInstanceDialog.IconLabel");
    public static string NewInstanceDialog_CreateButton => L("NewInstanceDialog.CreateButton");

    // EditInstanceDialog
    public static string EditInstanceDialog_Title => L("EditInstanceDialog.Title");
    public static string EditInstanceDialog_HeaderTitle => L("EditInstanceDialog.HeaderTitle");
    public static string EditInstanceDialog_GeneralSection => L("EditInstanceDialog.GeneralSection");
    public static string EditInstanceDialog_JavaMemorySection => L("EditInstanceDialog.JavaMemorySection");
    public static string EditInstanceDialog_JavaMemoryHint => L("EditInstanceDialog.JavaMemoryHint");
    public static string EditInstanceDialog_MinHeapLabel => L("EditInstanceDialog.MinHeapLabel");
    public static string EditInstanceDialog_MaxHeapLabel => L("EditInstanceDialog.MaxHeapLabel");
    public static string EditInstanceDialog_JvmArgsLabel => L("EditInstanceDialog.JvmArgsLabel");
    public static string EditInstanceDialog_JvmArgsWatermark => L("EditInstanceDialog.JvmArgsWatermark");
    public static string EditInstanceDialog_GameDirLabel => L("EditInstanceDialog.GameDirLabel");
    public static string EditInstanceDialog_GameDirWatermark => L("EditInstanceDialog.GameDirWatermark");
    public static string EditInstanceDialog_BrowseButton => L("EditInstanceDialog.BrowseButton");
    public static string EditInstanceDialog_WindowResolutionLabel => L("EditInstanceDialog.WindowResolutionLabel");
    public static string EditInstanceDialog_WidthShort => L("EditInstanceDialog.WidthShort");
    public static string EditInstanceDialog_HeightShort => L("EditInstanceDialog.HeightShort");
    public static string EditInstanceDialog_ResolutionHint => L("EditInstanceDialog.ResolutionHint");
    public static string EditInstanceDialog_SaveButton => L("EditInstanceDialog.SaveButton");
    public static string EditInstanceDialog_InstanceNameLabel => L("EditInstanceDialog.InstanceNameLabel");
    public static string EditInstanceDialog_IconLabel => L("EditInstanceDialog.IconLabel");

    // EditInstanceIconDialog
    public static string EditInstanceIconDialog_Title => L("EditInstanceIconDialog.Title");
    public static string EditInstanceIconDialog_HeaderTitle => L("EditInstanceIconDialog.HeaderTitle");
    public static string EditInstanceIconDialog_Subtitle => L("EditInstanceIconDialog.Subtitle");
    public static string EditInstanceIconDialog_SaveButton => L("EditInstanceIconDialog.SaveButton");

    // Common
    public static string Common_Cancel => L("Common.Cancel");
    public static string Common_Save => L("Common.Save");
    public static string Common_Create => L("Common.Create");
    public static string Common_OK => L("Common.OK");
    public static string Common_Yes => L("Common.Yes");
    public static string Common_No => L("Common.No");
    public static string Common_Close => L("Common.Close");
    public static string Common_Hide => L("Common.Hide");
    public static string Common_Browse => L("Common.Browse");

    // DeviceCodeDialog
    public static string DeviceCodeDialog_Title => L("DeviceCodeDialog.Title");
    public static string DeviceCodeDialog_HeaderTitle => L("DeviceCodeDialog.HeaderTitle");
    public static string DeviceCodeDialog_OpenPagePrompt => L("DeviceCodeDialog.OpenPagePrompt");
    public static string DeviceCodeDialog_EnterCodePrompt => L("DeviceCodeDialog.EnterCodePrompt");
    public static string DeviceCodeDialog_Footer => L("DeviceCodeDialog.Footer");
    public static string DeviceCodeDialog_CopyCode => L("DeviceCodeDialog.CopyCode");
    public static string DeviceCodeDialog_OpenBrowser => L("DeviceCodeDialog.OpenBrowser");

    // JoinServerDialog
    public static string JoinServerDialog_Title => L("JoinServerDialog.Title");
    public static string JoinServerDialog_HeaderTitle => L("JoinServerDialog.HeaderTitle");
    public static string JoinServerDialog_PickInstance => L("JoinServerDialog.PickInstance");
    public static string JoinServerDialog_NoInstancesPlaceholder => L("JoinServerDialog.NoInstancesPlaceholder");
    public static string JoinServerDialog_JoinButton => L("JoinServerDialog.JoinButton");

    // WorldsDialog
    public static string WorldsDialog_Title => L("WorldsDialog.Title");
    public static string WorldsDialog_HeaderTitle => L("WorldsDialog.HeaderTitle");
    public static string WorldsDialog_ResumeButton => L("WorldsDialog.ResumeButton");

    // NewHeadlessServerDialog
    public static string NewHeadlessServerDialog_Title => L("NewHeadlessServerDialog.Title");
    public static string NewHeadlessServerDialog_HeaderTitle => L("NewHeadlessServerDialog.HeaderTitle");
    public static string NewHeadlessServerDialog_Hint => L("NewHeadlessServerDialog.Hint");
    public static string NewHeadlessServerDialog_ServerNameLabel => L("NewHeadlessServerDialog.ServerNameLabel");
    public static string NewHeadlessServerDialog_DefaultServerName => L("NewHeadlessServerDialog.DefaultServerName");
    public static string NewHeadlessServerDialog_MinecraftVersionLabel => L("NewHeadlessServerDialog.MinecraftVersionLabel");
    public static string NewHeadlessServerDialog_LoadingManifestShort => L("NewHeadlessServerDialog.LoadingManifestShort");
    public static string NewHeadlessServerDialog_MaxHeapLabel => L("NewHeadlessServerDialog.MaxHeapLabel");
    public static string NewHeadlessServerDialog_PortLabel => L("NewHeadlessServerDialog.PortLabel");

    // SkinVariantDialog
    public static string SkinVariantDialog_Title => L("SkinVariantDialog.Title");
    public static string SkinVariantDialog_HeaderTitle => L("SkinVariantDialog.HeaderTitle");
    public static string SkinVariantDialog_Question => L("SkinVariantDialog.Question");
    public static string SkinVariantDialog_Hint => L("SkinVariantDialog.Hint");
    public static string SkinVariantDialog_Classic => L("SkinVariantDialog.Classic");
    public static string SkinVariantDialog_Slim => L("SkinVariantDialog.Slim");

    // CurseForgeOnboardingDialog
    public static string CurseForgeOnboardingDialog_Title => L("CurseForgeOnboardingDialog.Title");
    public static string CurseForgeOnboardingDialog_HeaderTitle => L("CurseForgeOnboardingDialog.HeaderTitle");
    public static string CurseForgeOnboardingDialog_Heading => L("CurseForgeOnboardingDialog.Heading");
    public static string CurseForgeOnboardingDialog_Step1Body => L("CurseForgeOnboardingDialog.Step1Body");
    public static string CurseForgeOnboardingDialog_Step2Button => L("CurseForgeOnboardingDialog.Step2Button");
    public static string CurseForgeOnboardingDialog_Step3Label => L("CurseForgeOnboardingDialog.Step3Label");
    public static string CurseForgeOnboardingDialog_KeyWatermark => L("CurseForgeOnboardingDialog.KeyWatermark");
    public static string CurseForgeOnboardingDialog_SaveButton => L("CurseForgeOnboardingDialog.SaveButton");
    public static string CurseForgeOnboardingDialog_CancelButton => L("CurseForgeOnboardingDialog.CancelButton");

    // Mods page CurseForge empty state
    public static string Mods_ConnectHeadline => L("Mods.ConnectHeadline");
    public static string Mods_ConnectSubhead => L("Mods.ConnectSubhead");
    public static string Mods_GetStartedButton => L("Mods.GetStartedButton");

    // Settings page Mods card
    public static string Settings_ModsHeader => L("Settings.ModsHeader");
    public static string Settings_CurseForgeStatusNotConfigured => L("Settings.CurseForgeStatusNotConfigured");
    public static string Settings_CurseForgeStatusConfigured => L("Settings.CurseForgeStatusConfigured");
    public static string Settings_SetUpCurseForgeButton => L("Settings.SetUpCurseForgeButton");
    public static string Settings_ChangeKeyButton => L("Settings.ChangeKeyButton");

    // ImportModpackDialog
    public static string ImportModpackDialog_Title => L("ImportModpackDialog.Title");
    public static string ImportModpackDialog_HeaderTitle => L("ImportModpackDialog.HeaderTitle");
    public static string ImportModpackDialog_ArchiveLabel => L("ImportModpackDialog.ArchiveLabel");
    public static string ImportModpackDialog_NoArchivePicked => L("ImportModpackDialog.NoArchivePicked");
    public static string ImportModpackDialog_InstanceNameLabel => L("ImportModpackDialog.InstanceNameLabel");
    public static string ImportModpackDialog_InstanceNameWatermark => L("ImportModpackDialog.InstanceNameWatermark");
    public static string ImportModpackDialog_Hint => L("ImportModpackDialog.Hint");
    public static string ImportModpackDialog_ImportButton => L("ImportModpackDialog.ImportButton");

    // ViewModel log messages
    public static string Log_AutoRefreshingOnStartup => L("Log.AutoRefreshingOnStartup");
    public static string Log_SilentMsSignInAttempt => L("Log.SilentMsSignInAttempt");
    public static string Log_AutoSignedInAs => L("Log.AutoSignedInAs");
    public static string Log_SilentSignInSkipped => L("Log.SilentSignInSkipped");
    public static string Log_LoadingVersionManifest => L("Log.LoadingVersionManifest");
    public static string Log_LoadedNVersions => L("Log.LoadedNVersions");
    public static string Log_LoadingInstances => L("Log.LoadingInstances");
    public static string Log_FetchingNews => L("Log.FetchingNews");
    public static string Log_LoadedNNewsArticles => L("Log.LoadedNNewsArticles");
    public static string Log_ReadingServersDat => L("Log.ReadingServersDat");
    public static string Log_LoadedNServers => L("Log.LoadedNServers");
    public static string Log_ReadingLauncherProfiles => L("Log.ReadingLauncherProfiles");
    public static string Log_LoadedNProfiles => L("Log.LoadedNProfiles");
    public static string Log_ScanningInstalledVersions => L("Log.ScanningInstalledVersions");
    public static string Log_FoundNInstalledVersions => L("Log.FoundNInstalledVersions");
    public static string Log_SigningInWithMicrosoft => L("Log.SigningInWithMicrosoft");
    public static string Log_SignedInAs => L("Log.SignedInAs");
    public static string Log_MicrosoftSignInPrompt => L("Log.MicrosoftSignInPrompt");
    public static string Log_SignedOut => L("Log.SignedOut");
    public static string Log_SavingSettings => L("Log.SavingSettings");
    public static string Log_SettingsSaved => L("Log.SettingsSaved");
    public static string Log_CouldNotSaveSettings => L("Log.CouldNotSaveSettings");
    public static string Log_ModsNoRepository => L("Log.ModsNoRepository");
    public static string Log_ModsSearching => L("Log.ModsSearching");
    public static string Log_ModsResultsCount => L("Log.ModsResultsCount");
    public static string Log_ModsNoRepositoryForInstall => L("Log.ModsNoRepositoryForInstall");
    public static string Log_ModsResolvingFiles => L("Log.ModsResolvingFiles");
    public static string Log_ModsNoMatchingFiles => L("Log.ModsNoMatchingFiles");
    public static string Log_ModsInstalling => L("Log.ModsInstalling");
    public static string Log_ModsInstallComplete => L("Log.ModsInstallComplete");
    public static string Log_ModsInstalledInInstance => L("Log.ModsInstalledInInstance");
    public static string Log_ModsRemoved => L("Log.ModsRemoved");

    // Error messages
    public static string Error_NoSession => L("Error.NoSession");
    public static string Error_SkinPickerUnavailable => L("Error.SkinPickerUnavailable");
    public static string Error_CapeOpsRequireMsAccount => L("Error.CapeOpsRequireMsAccount");
    public static string Error_SkinUploadCancelled => L("Error.SkinUploadCancelled");
    public static string Error_CannotDeleteAutoImported => L("Error.CannotDeleteAutoImported");
    public static string Error_CannotChangeAutoImportedIcon => L("Error.CannotChangeAutoImportedIcon");
    public static string Error_CannotEditAutoImported => L("Error.CannotEditAutoImported");
    public static string Error_ModpackImporterDisabled => L("Error.ModpackImporterDisabled");
    public static string Error_ModpackImportCancelled => L("Error.ModpackImportCancelled");
    public static string Error_InstanceExportUnavailable => L("Error.InstanceExportUnavailable");
    public static string Error_CannotExportAutoImported => L("Error.CannotExportAutoImported");
    public static string Error_ExportPickerUnavailable => L("Error.ExportPickerUnavailable");
    public static string Error_InstanceExportCancelled => L("Error.InstanceExportCancelled");
    public static string Error_InstanceImportUnavailable => L("Error.InstanceImportUnavailable");
    public static string Error_ImportPickerUnavailable => L("Error.ImportPickerUnavailable");
    public static string Error_InstanceImportCancelled => L("Error.InstanceImportCancelled");
}
